### ISSUE TITLE
shiny down?

### ISSUE THREAD

**Issue by sl-dashboard** [egap/metaketa-i#3]
I get two errors just by launching: 

`An error has occurred. Check your logs or contact the app author for clarification.`

**Comment by macartan** [comment]
link should go to here: https://egap.shinyapps.io/metaketa1/

**Comment by sl-dashboard** [comment]
thanks! just fyi, when you google "metaketa shiny" you get directed to this https://shiny.wzb.eu/apps/ipi/metaketa1/ which is the one showing error
